### ISSUE TITLE
Integrate a package manager

### ISSUE THREAD

**Issue by orhun** [orhun/linuxwave#10]
**Is your feature request related to a problem? Please describe.**

Currently, `linuxwave` is not packaged for any Zig package manager and the dependencies are simply git submodules. 

**Describe the solution you'd like**

It would be nice to utilize [zigmod](https://github.com/nektro/zigmod) and/or [gyro](https://github.com/mattnite/gyro).

**Describe alternatives you've considered**

None.

**Additional context**

See [zerve](https://github.com/floscodes/zerve) project's files (`gyro.zzz`, `zig.mod`) which sparked this idea.

**Comment by booniepepper** [comment]
As an alternative, Zig 0.11 ([scheduled for release Aug 3, 2023](https://ziglang.org/news/0.11.0-postponed-again/)) has a built-in package management system.

It's not quite a "package manager" in the sense of something like crates.io that has an index and central repository. The basic idea would be to simply add a `build.zig.zon` once Zig 0.11 is released. (And any other Zig 0.11 compatibility changes that will be required)

**Comment by orhun** [comment]
Thanks for the info @booniepepper! I would prefer to go with the built-in package manager when it is available soon. It would be nice to have it in #8 maybe. cc @yellowapple
