### ISSUE TITLE
FileNotFound error when building from source

### ISSUE THREAD

**Issue by TKK13909** [orhun/linuxwave#4]
**Describe the bug**

When I attempt to build from source following the instructions, I get the error: "FileNotFound: /home/tkk/temp/linuxwave/libs/zig-clap/clap.zig"

**To reproduce**

`
git clone https://github.com/orhun/linuxwave && cd linuxwave/
zig build -Drelease-safe
`

**Expected behavior**

The project should build with no errors

**Screenshots / Logs**
❯ zig build -Drelease-safe
warning: FileNotFound: /home/tkk/temp/linuxwave/libs/zig-clap/clap.zig
error: FileNotFound
error: linuxwave...
error: The following command exited with error code 1:
/usr/bin/zig build-exe /home/tkk/temp/linuxwave/src/main.zig -OReleaseSafe --cache-dir /home/tkk/temp/linuxwave/zig-cache --global-cache-dir /home/tkk/.cache/zig --name linuxwave --pkg-begin clap /home/tkk/temp/linuxwave/libs/zig-clap/clap.zig --pkg-end --pkg-begin file /home/tkk/temp/linuxwave/src/file.zig --pkg-end --pkg-begin gen /home/tkk/temp/linuxwave/src/gen.zig --pkg-end --pkg-begin wav /home/tkk/temp/linuxwave/src/wav.zig --pkg-end --pkg-begin build_options /home/tkk/temp/linuxwave/zig-cache/options/qMakyD73vBhS-mLFzE_KDtVFe5JLMb8_fa1uQfpzXJ_ZwUp24BkeEUgj8oneTF4J --pkg-end -fPIE --enable-cache
error: the following build command failed with exit code 1:
/home/tkk/temp/linuxwave/zig-cache/o/8205680e369cdd724044e5a08320985a/build /usr/bin/zig /home/tkk/temp/linuxwave /home/tkk/temp/linuxwave/zig-cache /home/tkk/.cache/zig -Drelease-safe

**Software information**

- Operating system: Arch Linux 6.2.11-arch1-1
- Zig version: 0.10.1
- Project version: ?

P.S. This is my first bug report on GitHub. I don't quite know how to get Markdown to work properly

**Comment by orhun** [comment]
I forgot to add a gitmodule update step to README.md. It is now added in https://github.com/orhun/linuxwave/commit/ca62679f2c72ad424070be0113bd5e95c01af628

You simply need to update the git submodules before building:

```sh
git submodule update --init --recursive
```
